approve_by_comment: true
approve_regex: ^Approved
reject_regex: ^Rejected
reset_on_push: true
reset_on_reopened: true
reviewers:
  members:
  - alexchmykhalo
  - Guitarheroua
  name: default
  required: 1
