version: 0.0.1-{build}-{branch}
pull_requests:
  do_not_increment_build_number: true
environment:
  QT_INSTALL_ROOT: C:\Qt\5.7\msvc2015_64
build_script:
- cmd: >-

    %QT_INSTALL_ROOT%\bin\qtenv2.bat

    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64  

    cd %APPVEYOR_BUILD_FOLDER%\pllug-presentation-system

    qmake CONFIG+=release

    nmake
    
    %QT_INSTALL_ROOT%\bin\windeployqt --qmldir %APPVEYOR_BUILD_FOLDER%\pllug-presentation-system\resources %APPVEYOR_BUILD_FOLDER%\pllug-presentation-system\release 

    cd %APPVEYOR_BUILD_FOLDER%\tests

    qmake CONFIG+=release

    nmake

    nmake tests
    
    cd %APPVEYOR_BUILD_FOLDER%\pllug-presentation-system
  
    7z a pps2.zip release\

after_build:    
artifacts:
 - path: pps2.zip
   name: pps2
appveyor PushArtifact pps2
