version: 0.0.1-{build}-{branch}
pull_requests:
  do_not_increment_build_number: true
environment:
  QT_INSTALL_ROOT: C:\Qt\5.7\msvc2015_64
build_script:
- cmd: >-  
    
    %QT_INSTALL_ROOT%\bin\qtenv2.bat

    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

    cd %APPVEYOR_BUILD_FOLDER%\pllug-presentation-system
	
	git submodule -q update --init

    qmake CONFIG+=release

    nmake

    cd %APPVEYOR_BUILD_FOLDER%\tests

    qmake CONFIG+=release

    nmake

    nmake tests
