version: 0.0.1-{build}-{branch}
pull_requests:
  do_not_increment_build_number: true
environment:
  QT_INSTALL_ROOT: C:\Qt\5.7\msvc2015_64
build_script:
- cmd: >-

    %QT_INSTALL_ROOT%\bin\qtenv2.bat

    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64  

    cd %APPVEYOR_BUILD_FOLDER%\pllug-presentation-system

    qmake CONFIG+=release

    nmake
    
    %QT_INSTALL_ROOT%\bin\windeployqt --qmldir %APPVEYOR_BUILD_FOLDER%\pllug-presentation-system\resources %APPVEYOR_BUILD_FOLDER%\pllug-presentation-system\release

    install:
     - cmd: "2015 Update 1\vc_redist.x64.exe" /install /passive /norestart 

    cd %APPVEYOR_BUILD_FOLDER%\tests

    qmake CONFIG+=release

    nmake

    nmake tests
