version: 0.0.1-{build}-{branch}
pull_requests:
  do_not_increment_build_number: true
environment:
  QT_INSTALL_ROOT: C:\Qt\5.7\msvc2015_64
  QT_IFW_ROOT: C:\Qt\QtIFW2.0.3
  appveyor_repo_tag: true

build_script:
- cmd: >-

    %QT_INSTALL_ROOT%\bin\qtenv2.bat

    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64  

    cd %APPVEYOR_BUILD_FOLDER%\pllug-presentation-system

    qmake CONFIG+=release

    nmake
    
    %QT_INSTALL_ROOT%\bin\windeployqt --qmldir %APPVEYOR_BUILD_FOLDER%\pllug-presentation-system\resources %APPVEYOR_BUILD_FOLDER%\pllug-presentation-system\release 

    cd %APPVEYOR_BUILD_FOLDER%\tests

    qmake CONFIG+=release

    nmake

    nmake tests
    
    cd %APPVEYOR_BUILD_FOLDER%\pllug-presentation-system
    
    move %APPVEYOR_BUILD_FOLDER%\vc_redist.x64.exe %APPVEYOR_BUILD_FOLDER%\pllug-presentation-system\release 
  
    7z a pps2.zip release\
    
    move %APPVEYOR_BUILD_FOLDER%\pps2.zip %APPVEYOR_BUILD_FOLDER%\setup\packages\com.vendor.product\data
    
    cd %APPVEYOR_BUILD_FOLDER%\setup
    
    %QT_IFW_ROOT%\bin\binarycreator.exe -c config\config.xml -p packages setup.exe
    
    

after_build:    
artifacts:
 - path: pps2.zip
   name: pps2

deploy:
- provider: GitHub
  artifact: pps2 
  auth_token: Ef75dfrZSDSRMOmdjgpr0s42xA7JTPT3MKF+AGqpQwI=  
  draft: false
  prerelease: false
  description: '.zip folder added'
  #release: v1.0
  on:
    branch: feature-24-Deployment-script                
    appveyor_repo_tag: true

